name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
 
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Chec out code into the go module directory
      uses: actions.checkout@v2

    - name: Test
      run: make test
